name: Ping Render API

on:
  schedule:
    - cron: '* * * * *'   # Every 1 minute (UTC)
  push:                    # Trigger on push to any branch
    branches:
      - main               # Trigger on push to the 'main' branch (you can change this to match your branch name)
  workflow_dispatch:        # Manual trigger option

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl the Render API
        run: curl -s https://octo-pinned-api.onrender.com/api/pinned
