name: Ping Render API

on:
  schedule:
    - cron: '*/3 * * * *'  # Every 3 minutes (UTC)
  push:
    branches:
      - main  # Trigger the workflow on push to the 'main' branch

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl the Render API with Timestamp
        id: api_request
        run: |
          # Capture the current time
          current_time=$(date +"%Y-%m-%d %H:%M:%S")

          # Perform the API request
          response=$(curl -s https://octo-pinned-api.onrender.com/api/pinned)

          # Send the response to Slack
          curl -X POST -H "Content-type: application/json" \
            --data "{\"text\":\"The workflow ran at: $current_time\\nAPI Response: $response\"}" \
            ${{ secrets.SLACK_WEBHOOK_URL }}

          # Print to GitHub Actions log for confirmation
          echo "Timestamp: $current_time"
          echo "API Response: $response"

          # Store the response in an environment variable for further steps
          echo "API_RESPONSE=$response" >> $GITHUB_ENV
          echo "TIMESTAMP=$current_time" >> $GITHUB_ENV

      - name: Show the API response with Timestamp
        run: |
          # Access the environment variables set in the previous step
          echo "The API responded at ${{ env.TIMESTAMP }} with: ${{ env.API_RESPONSE }}"
